// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using pax.blazor.survey.Db;

namespace pax.blazor.survey.Migrations
{
    [DbContext(typeof(SurveyContext))]
    partial class SurveyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.1.20451.13");

            modelBuilder.Entity("OptionQuestion", b =>
                {
                    b.Property<int>("OptionsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuestionsID")
                        .HasColumnType("INTEGER");

                    b.HasKey("OptionsID", "QuestionsID");

                    b.HasIndex("QuestionsID");

                    b.ToTable("OptionQuestion");
                });

            modelBuilder.Entity("QuestionSurvey", b =>
                {
                    b.Property<int>("QuestionsID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SurveysID")
                        .HasColumnType("INTEGER");

                    b.HasKey("QuestionsID", "SurveysID");

                    b.HasIndex("SurveysID");

                    b.ToTable("QuestionSurvey");
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.Property<int>("SurveysID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UsersID")
                        .HasColumnType("INTEGER");

                    b.HasKey("SurveysID", "UsersID");

                    b.HasIndex("UsersID");

                    b.ToTable("SurveyUser");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Answer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnswerValue")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OptionID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponseID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("OptionID");

                    b.HasIndex("Pos");

                    b.HasIndex("ResponseID");

                    b.HasIndex("Selected");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Option", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptionValue")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pos")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Options");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Question", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Interview")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Pos")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Response", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Feedback")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pos")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("QuestionID")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Selected")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SurveyID")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("Pos");

                    b.HasIndex("QuestionID");

                    b.HasIndex("SurveyID");

                    b.HasIndex("UserID");

                    b.ToTable("Responses");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Survey", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AllowAnonymouse")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Expire")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pos")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowProgress")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowResult")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Surveys");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OptionQuestion", b =>
                {
                    b.HasOne("pax.blazor.survey.Models.Option", null)
                        .WithMany()
                        .HasForeignKey("OptionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pax.blazor.survey.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("QuestionSurvey", b =>
                {
                    b.HasOne("pax.blazor.survey.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pax.blazor.survey.Models.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SurveyUser", b =>
                {
                    b.HasOne("pax.blazor.survey.Models.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveysID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pax.blazor.survey.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Answer", b =>
                {
                    b.HasOne("pax.blazor.survey.Models.Option", "Option")
                        .WithMany("Answers")
                        .HasForeignKey("OptionID");

                    b.HasOne("pax.blazor.survey.Models.Response", "Response")
                        .WithMany("Answers")
                        .HasForeignKey("ResponseID");

                    b.Navigation("Option");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Response", b =>
                {
                    b.HasOne("pax.blazor.survey.Models.Question", "Question")
                        .WithMany("Responses")
                        .HasForeignKey("QuestionID");

                    b.HasOne("pax.blazor.survey.Models.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyID");

                    b.HasOne("pax.blazor.survey.Models.User", "User")
                        .WithMany("Responses")
                        .HasForeignKey("UserID");

                    b.Navigation("Question");

                    b.Navigation("Survey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Option", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Question", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Response", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.Survey", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("pax.blazor.survey.Models.User", b =>
                {
                    b.Navigation("Responses");
                });
#pragma warning restore 612, 618
        }
    }
}
